// Generated file - do not edit
// Generated by native_splash_screen_cli

import native_splash_screen_macos

class ProfileNativeSplashScreenConfiguration: NativeSplashScreenConfigurationProvider {

    // MARK: - Splash screen properties
    let windowWidth: Int = 500
    let windowHeight: Int = 250

    // MARK: - Window Title
    let windowTitle: String = "My Flutter App (Profile)"

    // MARK: - Animation control
    let withAnimation: Bool = true

    // MARK: - Image properties
    let imageFileName: String = "splash_screen_profile.png"
    let imageWidth: Int = 500
    let imageHeight: Int = 250
}
