name: native_splash_screen
description: >
  A fully configurable native splash screen plugin for Flutter apps,
  supporting static linking, runtime animations, and CLI-based asset generation.
repository: https://github.com/anicine/native_splash_screen
version: 3.0.0

topics:
  - splash-screen
  - splash-image
  - splash-window

platforms:
  linux:
  windows:
  macos:

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    platforms:
      linux:
        default_package: native_splash_screen_linux
      windows:
        default_package: native_splash_screen_windows
      macos:
        default_package: native_splash_screen_macos

dependencies:
  flutter:
    sdk: flutter

  native_splash_screen_platform_interface: ">=3.0.0 <4.0.0"
  native_splash_screen_linux: ">=3.0.0 <4.0.0"
  native_splash_screen_windows: ">=3.0.0 <4.0.0"
  native_splash_screen_macos: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_lints:
