name: native_splash_screen_cli
description: "A CLI tool that generates native splash screen code for Flutter apps based on a YAML config file."
version: 3.0.0
repository: https://github.com/anicine/native_splash_screen

platforms:
  linux:
  windows:
  macos:

environment:
  sdk: ^3.4.0

dependencies:
  yaml: ^3.1.3
  args: ^2.7.0
  logger: ^2.5.0
  image: ^4.5.4
  path: ^1.9.0

dev_dependencies:
  lints:
